name: Flowers
version: '1.0.0'
main: dev.luan.flowers.BetterFlowers
api-version: '1.20'
author: luannndev
description: A strong tool to create custom flowers & use them as a brush.

commands:
  flower:
    description: Opens a menu to create custom flower.
    aliases:
      - f
      - F
  flowerbrush:
    description: Opens a menu to create flower brush.
    aliases:
      - fb
      - Fb
      - fB
      - FB
  undoflower:
    description: Undo your last placed flower/brush.
    aliases:
      - uf
      - Uf
      - uF
      - UF